##Crea tu propia función
La primera parte de esta actividad consiste en crear una función que trunque un número.
Primero crearemos la función t que trunca un número a 4 cifras .

Después crearemos la función "trunca" que trunca un número a la cantidad de cifras que se le indique.

Tip: Puedes revisar el notebook de la clase del lunes ya que ya hicimos algo parecido

Primero veamos como podemos truncar 1.499999 a 1.499, sigue las instrucciones, la función la crearemos más adelante

In [4]:
 x=1.499999 #crea tu variable x igual a 1.499999
x=str(x) #convierte a str tu variable x usando la función correcta
type(x)#utiliza type para ver que x sí sea str, si no lo es, corrije lo que te faltó en el renglón anterior

str

In [5]:
x=list(str(x)) #Convierte x a una lista usando la función que me convierte str o tuplas a listas
print(x) #imprime x para ver que sí sea una lista donde cada digito es un elemento, si no lo es corrije lo que te faltó en el renglón anterior

['1', '.', '4', '9', '9', '9', '9', '9']


In [6]:
x=x[:5] #Utiliza la función adecuada para borrar todos los digitos a partir del de indice 5
print(x) #imprime x para ver que sí funcionó (y te quedó el 1.499 separado)

['1', '.', '4', '9', '9']


In [7]:
x="".join(x)#regresalo a un solo string usando join
print(x) #imprime x para ver que sí se haya juntado
type(x) #verifica que la x sea un string usando la función que nos dice el tipo de variable

1.499


str

In [8]:
float(x)#Cambia la x a float

1.499

Ahora crearemos la función t, toma en cuenta lo siguiente:
1. Debes definir la función t usando def y la sintaxis vista en clase, debe tener un argumento (podemos llamarle x)
2. Dentro de la función debes de:

*   convertir x a string
*   luego convertirlo a lista
*   borrarle los elementos a partir del de indice 5
*   volver a juntar los elementos usando join
*   convertir x a float
*   terminar la función con return x

Esta función truncará el número a 4 cifras siempre que no sea mayor o igual a 10000


In [12]:
def t(x):
  xstr=str(x)
  xlist =list(xstr)
  if x >=10000:
    return x
  xlist=xlist[:5]
  xstr=''.join(xlist)
  x=float(xstr)
  return x

In [13]:
t(1.29292929) #utiliza tu función t para truncar el número 1.29292929 y ve que funcione

1.292

Ahora vamos a mejorar la función creando la función trunca:
Copia y pega la celda donde definiste la función t, cambiale el nombre a trunca y agrega otro argumento al lado de la x,
puedes ponerle y.

Ese segundo argumento será el número de cifras que deseas, dentro de tu función cambia el 5 por y+1.
Debes ponerle más 1 por que el punto decimal ocupa un lugar.
Después revisa que funcione la función escribiendo trunca(1.2929292929,7) debería darte 1.292929

In [15]:
def trunca(x, y):
  xstr=str(x)
  xlist =list(xstr)
  if x>=y:
    return 'Error: x debe ser menor que y'
  if x>=10000:
    return x
  xlist=xlist[:y+1]
  xstr=''.join(xlist)
  x=float(xstr)
  return x

In [16]:
trunca(1.2929292929,7)

1.292929

Numpy

Es una librería (abreviatura de numeric python). Nos permite usar arreglos (matrices) y por lo tanto realizar operaciones que no se podrían hacer con listas

In [17]:
import numpy as np #Usualmente se importa como np (para no tener que repetir la palabra numpy cada que usemos una de sus funciones)

Si tenemos dos listas y queremos dividir sus elementos no se puede directamente. Ejemplo:

In [18]:
L1=[1,2,3]
L2=[4,4,9]

In [19]:
L1/L2 #Veamos como da error al dividir dos listas

TypeError: ignored

Con numpy podemos crear dos arreglos y luego dividirlos

In [23]:
A1=np.array(L1) #La función array convierte una lista a un arreglo
print(A1)

[1 2 3]


In [24]:
A2=np.array(L2)
print(A2) #Haz lo mismo con L2, llamale al arreglo A2

[4 4 9]


In [25]:
A1/A2 #Divide A1/A2

array([0.25      , 0.5       , 0.33333333])

En la clase del jueves veremos más operaciones que se pueden realizar con arreglos y otras de sus caracteristicas