In [3]:
#importa numpy y pandas
import numpy as np
import pandas as pd

Operadores de comparación

In [4]:
'A'>'a' #Checar si las mayúsculas son mayores que las minúsculas con un comparador

False

In [5]:
Ar=np.array([7,5,2,-3,0,18])
Ar2=np.array([3,2,1,0,0,20])

In [6]:
Ar>5 #Compara el arreglo con un número, (ya lo habiamos hecho antes)

array([ True, False, False, False, False,  True])

In [7]:
Ar[Ar>5] #Seleccionamos los datos de Ar que sean mayores a 5

array([ 7, 18])

In [8]:
3!=2 #Simbolo para decir "diferente" o "igual negado"

True

In [9]:
True==1 #Checar si True es igual a 1

True

In [10]:
Ar>Ar2 #Comparar los dos arreglos, ¿Qué elementos son más grandes en Ar que en Ar2?

array([ True,  True,  True, False, False, False])

Primer operador lógico: and

In [11]:
#Creamos x, y y z para el ejemplo
x=0
y=1
z=2

In [12]:
#and nos devuelve True cuando las dos condiciones son verdad
x<z and y<z

True

In [13]:
x=10 #¿cómo checariamos que x sea mayor que 5 pero menor que 20?
x>5 and x<20

True

In [14]:
not x>5  #not

False

Comparador or, da verdadero con que alguno de los dos es verdadero

In [15]:
x>5 or x<0 #¿Cómo podríamos checar que x cumpla con que sea mayor a 5 o menor a 0?


True

In [16]:
# ¿Cómo podríamos poner nor? nor solo nos da verdadero cuando los dos son falsos
#Por ejemplo checar que la x ni sea mayor a 15 ni menor a 5
not (x>15 or x<5)

True

Filtrado de arreglos y pandas

In [17]:
nombres=np.array(["María","Ana","Sofía","José","Juan"])#Trabajaremos con las calificaciones de 5 alumnos, sus nombres y calificaciones están en los arreglos de numpy
calif=np.array([10,9.5,5,7.2,8])

In [18]:
calif>8 #¿Qué alumnos tienen una calificación mayor a 8?

array([ True,  True, False, False, False])

In [19]:
nombres[calif>8]

array(['María', 'Ana'], dtype='<U5')

Para usar and o or con arreglos se usa np.logical_and(cond,cond)

In [20]:
nombres[np.logical_and(calif>=6,calif<9)]#¿Qué alumnos tienen una calificación aprobatoria (con 6 aprueban) pero menor a 9

array(['José', 'Juan'], dtype='<U5')

In [21]:
pand=pd.DataFrame({"col1":["Hugo","Paco","Luis"],"col2":[5,8,20]})

In [22]:
print(pand)

   col1  col2
0  Hugo     5
1  Paco     8
2  Luis    20


In [23]:
pand["col2"]>7

0    False
1     True
2     True
Name: col2, dtype: bool

¿Qué nombres tienen un número mayor a 7? (Filtrar)

In [24]:
pand['col1'][pand['col2']>7]

1    Paco
2    Luis
Name: col1, dtype: object

Hagamos un mini programa que nos diga si la variable es par o impar

In [25]:
a=32 #a será la variable a evaluar

In [26]:
if a%2==0:
  print('a es par')
  print('a es divisible entre dos')
else:
  print('a no es par')

a es par
a es divisible entre dos


Ahora haremos un programa que nos diga si es par y si no es, que cheque si es divisible entre 3


In [27]:
if a%2==0:
  print('a es par')
elif a%3==0:
  print('es divisible entre tres')
else:
  print('no es par ni divisible entre tres')

a es par


In [28]:
a=5

Filtrado de Pandas

In [29]:
from google.colab import drive #Librería necesaria para poder importar archivos desde el drive de google
drive.mount('/content/drive')

Mounted at /content/drive


Hoy filtraremos los datos de servicios de salud del INEGI, usaremos las columnas descritas en el diccionario dic1 y el archivo de INE_ENTIDAD_2020.CSV

In [30]:
dic={"POBTOT":["Población total"],"PSINDER": ["Personas sin seguro"], "PDER_SS":["Personas con seguro médico"],"PDER_IMSS":["Personas afiliadas al IMSS"], "PDER_ISTE":["Personas afiliadas al ISSSTE"],"PDER_ISTEE":["Personas afiliadas al ISSSTE ESTATAL"],"PAFIL_PDOM":["Personas afiliadas a servicios de salud en PEMEX, Defensa o Marina"],"PDER_SEGP":["Personas afiliadas con el Instituto para el Bienestar"],"PDER_IMSSB":["Personas afiliadas al IMSS Bienestar"],"PAFIL_IPRI":["Personas afiliadas a servicios privados"],"PAFIL_OTRA":["Personas afiliadas a otra"]}

In [31]:
dic.keys()

dict_keys(['POBTOT', 'PSINDER', 'PDER_SS', 'PDER_IMSS', 'PDER_ISTE', 'PDER_ISTEE', 'PAFIL_PDOM', 'PDER_SEGP', 'PDER_IMSSB', 'PAFIL_IPRI', 'PAFIL_OTRA'])

In [32]:
dfdic=pd.DataFrame(dic) #convertir dic1 a dataframe

In [33]:
dfdic

POBTOT              PSINDER                     PDER_SS  \
0  Población total  Personas sin seguro  Personas con seguro médico   

                    PDER_IMSS                     PDER_ISTE  \
0  Personas afiliadas al IMSS  Personas afiliadas al ISSSTE   

                             PDER_ISTEE  \
0  Personas afiliadas al ISSSTE ESTATAL   

                                          PAFIL_PDOM  \
0  Personas afiliadas a servicios de salud en PEM...   

                                           PDER_SEGP  \
0  Personas afiliadas con el Instituto para el Bi...   

                             PDER_IMSSB  \
0  Personas afiliadas al IMSS Bienestar   

                                PAFIL_IPRI                 PAFIL_OTRA  
0  Personas afiliadas a servicios privados  Personas afiliadas a otra

En la siguiente celda estamos importando algunas columnas del csv

In [34]:
salud=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/INE_ENTIDAD_2020.CSV",encoding="ISO-8859-1",usecols=("NOM_ENT ",'POBTOT', 'PSINDER', 'PDER_SS', 'PDER_IMSS', 'PDER_ISTE', 'PDER_ISTEE', 'PAFIL_PDOM', 'PDER_SEGP', 'PDER_IMSSB', 'PAFIL_IPRI', 'PAFIL_OTRA'))

In [35]:
salud.head(10) #Veamos los primeros 5 renglones

NOM_ENT    POBTOT  PSINDER  PDER_SS  PDER_IMSS  PDER_ISTE  \
0        Aguascalientes  1425607   262088  1161139     780525      92771   
1       Baja California  3769020   836317  2905265    1995530     152274   
2   Baja California Sur   798447   129270   664122     408856     101745   
3              Campeche   928363   203304   719677     288186      62638   
4  Coahuila de Zaragoza  3146771   597373  2540708    2085705     193655   
5                Colima   731391   123074   605947     362244      49082   
6               Chiapas  5543828  1814782  3698663     672681     212030   
7             Chihuahua  3741869   574108  3156294    2043251     172774   
8      Ciudad de México  9209944  2502789  6689012    3881545    1128554   
9               Durango  1832650   461394  1366665     744664     185483   

   PDER_ISTEE  PAFIL_PDOM  PDER_SEGP  PDER_IMSSB  PAFIL_IPRI  PAFIL_OTRA  
0        3786        3196     271996        1680       31789        3179  
1       86380       14012     515855       19862      131967       44490  
2        2549       10772     139342        3576       12335        2516  
3        2070       32088     327334        8950        7441        2914  
4        6136        8001     181821       12289       82868       30846  
5        1259       11047     179704        2774        9344        3016  
6       46562       38656    2538415      169403       32965       31976  
7       28073       10831     688684       31733      127454      120058  
8       12484      104474    1203824       21158      444160       93084  
9        7012        8406     404554       16703       16765        5967

Cambiaremos la tabla para que los indices sean la columna de los estados

In [36]:
 salud.set_index("NOM_ENT ", inplace=True) #inplace True para que modifique el panda original

In [37]:
salud.head() #Veamos que se haya hecho el cambio

POBTOT  PSINDER  PDER_SS  PDER_IMSS  PDER_ISTE  \
NOM_ENT                                                                 
Aguascalientes        1425607   262088  1161139     780525      92771   
Baja California       3769020   836317  2905265    1995530     152274   
Baja California Sur    798447   129270   664122     408856     101745   
Campeche               928363   203304   719677     288186      62638   
Coahuila de Zaragoza  3146771   597373  2540708    2085705     193655   

                      PDER_ISTEE  PAFIL_PDOM  PDER_SEGP  PDER_IMSSB  \
NOM_ENT                                                               
Aguascalientes              3786        3196     271996        1680   
Baja California            86380       14012     515855       19862   
Baja California Sur         2549       10772     139342        3576   
Campeche                    2070       32088     327334        8950   
Coahuila de Zaragoza        6136        8001     181821       12289   

                      PAFIL_IPRI  PAFIL_OTRA  
NOM_ENT                                       
Aguascalientes             31789        3179  
Baja California           131967       44490  
Baja California Sur        12335        2516  
Campeche                    7441        2914  
Coahuila de Zaragoza       82868       30846

Selecciona los estados que tienen una población con seguro medico mayor a 5 millones

In [38]:
salud['PDER_SS']>5000000 #2 Compara la columna de seguro médico con 5 millones

NOM_ENT 
Aguascalientes                     False
Baja California                    False
Baja California Sur                False
Campeche                           False
Coahuila de Zaragoza               False
Colima                             False
Chiapas                            False
Chihuahua                          False
Ciudad de México                    True
Durango                            False
Guanajuato                         False
Guerrero                           False
Hidalgo                            False
Jalisco                             True
México                              True
Michoacán de Ocampo                False
Morelos                            False
Nayarit                            False
Nuevo León                         False
Oaxaca                             False
Puebla                             False
Querétaro                          False
Quintana Roo                       False
San Luis Potosí                    False
Sinaloa

In [39]:
A=salud[salud['PDER_SS']>5000000]#Ponemos la condición como índice y así seleccionamos los renglones que la cumplen
#guardamos en la variable A

In [40]:
A.index #si solo quiero los nombres pido ver los indices

Index(['Ciudad de México', 'Jalisco', 'México',
       'Veracruz de Ignacio de la Llave'],
      dtype='object', name='NOM_ENT ')

In [41]:
salud[salud['PDER_SS']>5000000].index#En el mismo renglón

Index(['Ciudad de México', 'Jalisco', 'México',
       'Veracruz de Ignacio de la Llave'],
      dtype='object', name='NOM_ENT ')

¿Qué estados tienen una población con seguro médico mayor al 60% de su población estatal pero menor al 70%? O ¿Qué estados tienen entre un 60% y un 70% de su población asegurada?

In [74]:
salud[np.logical_and(salud['PDER_IMSS']>4000000,salud['PAFIL_IPRI']>400000)].index #estados con una población con seguro mayor al 60% de la población pero menor al 70%

Index([], dtype='object', name='NOM_ENT ')

In [55]:
print(B)

Index(['Chiapas', 'México', 'Oaxaca', 'Puebla',
       'Veracruz de Ignacio de la Llave'],
      dtype='object', name='NOM_ENT ')


In [75]:
x>3

True

In [76]:
x>5

True

In [84]:
6>3 or 6>5

True